config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'edit_public_page/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'submitemail', to: 'email_submission#index'
  post 'send_email', to: 'email_submission#send_email'
  get 'reset/:token', to: 'password_reset#reset'
  post 'submit_reset', to: 'password_reset#change_password'

  root 'home#index'

  get '/login', to: 'sessions#new', as: 'sessions_new'
  post '/login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get '/dashboard', to: 'dashboard#main', as: 'dashboard'
  get '/dashboard/hours', to: 'hours#index', as: 'hours'
  get '/dashboard/hours/new', to: 'hours#new', as: 'new_hour'
  post '/dashboard/hours', to: 'hours#create', as: 'create_hour'
  delete '/dashboard/hours', to: 'hours#destroy', as: 'delete_hour'

  post '/services', to: 'services#create'
  get '/services', to: 'services#new'

  get '/public/:username/services/:id', to: 'services#show', as: 'show_service'

  delete '/deleteservices/:id/hide', to: 'services#hide', as: 'hide_service'
  post '/togglepublish/:id', to: 'services#togglepublish', as: 'service_publish'

  get '/servicesindex', to: 'services#index'

  post '/editService/:token', to: 'services#submit_edit'
  get 'editService/:token', to: 'services#edit_page', as: 'edit_service'

  get 'public/:username', to: 'public_page#show', as: 'public_page'
  get '/edit_public_page', to: 'edit_public_page#index', as: 'edit_public_page'

  get 'appointments/:id/edit', to: 'appointments#edit', as: 'edit_appointment'
  patch 'appointments/:id', to: 'appointments#update', as: 'update_appointment'
  delete 'appointments/:id', to: 'appointments#destroy', as: 'delete_appointment'

  get '/apts/:username', to: 'user_appointments#show', as: 'userappointments'

  patch '/update/user_profile', to: 'edit_public_page#update', as: 'edit_public_page_update'
  get '/public/:username/:service_id/create/appointment', to: 'appointments#index', as: 'appointments_page_index'
  post '/public/:username/:service_id/create/appointment/submit', to: 'appointments#create_submit',  as: 'appointments_page_create_submit'
  get '/appointment/get/timings/:username/:start_date', to: 'appointments#fetch_slot_times_api',  as: 'appointments_page_fetch_slot_times_for_date'
end

app/models/service.rb
# frozen_string_literal: true

class Service < ApplicationRecord
  belongs_to :user
  has_many :appointments

  validates :name, presence: true, length: { maximum: 20 }
  validates :short_description, presence: true, length: { maximum: 60 }
  validates :description, length: { maximum: 10000 }
  validates :price, presence: true, numericality: { greater_than: 0, less_than: 10000 }
  validates :duration, presence: true, numericality: { greater_than: 0, less_than: 1440 }
  validate :price_is_valid_precision

  def price_is_valid_precision
    return unless price.to_f != price.to_f.round(2)

    errors.add(:price, 'is invalid. Too many decimal places.')
  end
end

app/controllers/services_controller.rb
# frozen_string_literal: true

class ServicesController < ApplicationController
  before_action :get_current_user
  before_action :redirect_if_logged_out, except: %i[show]

  def new
    @service = Service.new
  end

  def create
    @service = @current_user.services.new(service_params)
    @service.user_id = @current_user.user_id
    if @service.save
      redirect_to servicesindex_path, success: 'Service was successfully created.'
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit_page
    @service = @current_user.services.find_by(id: params[:token])
    if @service.nil?
      render plain: 'Service does not exist.'
    else
      render :edit_service
    end
  end

  def submit_edit
    @service = @current_user.services.find_by(id: params[:token])
    if @service.nil?
      flash[:error] = 'Service not found'
      render plain: 'Service does not exist.'
    elsif @service.update(service_params)
      redirect_to servicesindex_url, success: "Successfully edited service #{@service.name}."
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  def togglepublish
    @service = @current_user.services.find_by(id: params[:id], user_id: session[:user_id])
    if @service.nil?
      flash[:error] = 'Service not found'
      render plain: 'Service does not exist.'
    elsif
      # Toggle publish status
      if @service.update(is_published: !@service.is_published)
        redirect_to servicesindex_url
      else
        redirect_to servicesindex_url, error: "Failed to publish service."
      end
    end
  end

  def show
    @username = params[:username]
    service = Service.find_by(id: params[:id])
    if service.nil? || !service.is_published
      @service = nil
    else
      @service_owner ||= User.find_by(user_id: service.user_id)
      @service = service
    end
  end

  def index
    @services = @current_user.services.where(hidden: false)
  end

  def hide
    @service = @current_user.services.find_by(id: params[:id])
    
    if @service.update(hidden: true)  # Add a 'hidden' boolean column to the 'services' table
      redirect_to servicesindex_path, notice: 'Service deleted successfully.'
    else
      redirect_to servicesindex_path, notice: 'Service failed to delete.'
    end
  end

  private

  def service_params
    params.require(:service).permit(:name, :short_description, :description, :price, :duration)
  end

  def get_current_user
    @current_user ||= User.find_by(user_id: session[:user_id])
  end

  def redirect_if_logged_out
    redirect_to login_url if @current_user.nil?
  end
end

app/helpers/services_helper.rb
# frozen_string_literal: true

module ServicesHelper
end

app/views/services/edit_service.html.erb
<html>
  <head>
    <title>Service</title>
    <%= stylesheet_link_tag 'edit_service', media: 'all' %>
  </head>
  <body>
    <div class="service-container">
      <h1>Edit Service</h1>
      <%= form_with(model: @service, url: "", method: "post", local: true) do |form| %>
        <%= form.label :name %>
        <%= form.text_field :name %>
        
        <%= form.label :short_description %>
        <%= form.text_area :short_description , class: 'ip'%>

        <%= form.label :description %>
        <%= form.text_area :description , class: 'ip'%>

        <%= form.label :price %>
        <div class="field-unit-wrapper">
          <p>$</p>
          <%= form.number_field :price, { value: format("%.2f", @service.price), step: 0.01, class: 'ip', style: 'margin: 0'} %>
        </div>
        <%= form.label :duration %>
        <div class="field-unit-wrapper">
          <%= form.number_field :duration , { class: 'ip input-no-margin', style: 'margin: 0' } %>
          <p>minutes</p>
        </div>

        <div style="display: flex; gap: 20px">
          <%= link_to 'Cancel', servicesindex_path, class: 'button cancel-button' %>
          <%= form.submit "Save", class: 'button' %>
        </div>
        <% if flash[:error].present? %>
          <div>
            <%= flash[:error] %>
          </div>
        <% end %>
      <% end %>

      <%= button_to 'Delete Service', hide_service_path(@service), method: :delete, id: "delete-service-#{@service.id}", class: 'button delete-button' %>
      
    </div>
    

  </body>
</html>

app/views/services/index.html.erb
<html>
  <head>
    <title>Service</title>

    <%= stylesheet_link_tag 'service', media: 'all' %>
  </head>
  <body>
  <div class="navbar">
    <h1 class="title">Services</h1>
    <div class="navbar-links">
    <%= link_to 'Create New Service', services_path%>
    <%= link_to "Back to Dashboard", dashboard_path %>
    <%= link_to 'Logout', logout_path, method: :delete %>
  </div>
    
  </div>
  
  <% flash.each do |key, message|%>
    <div class="alert">
      <%= message%>
    </div>
  <%end%>

  <div class="days-container-2">
   
        <% @services.sort_by(&:id).each do |service| %>
          <div class="day-container-2">
        

            <h3><%= service.name %></h3>
            <div class="time-container-2">
            <p><strong>Description:  </strong><%= service.short_description %></p>
            <p><strong>Price:  </strong>$<%= format("%.2f", service.price) %></p>
            <p><strong>Duration:  </strong><%= service.duration / 60 > 0 ? (service.duration / 60).to_s + "hr " : "" %>
            <%= service.duration % 60 > 0 ? (service.duration % 60).to_s + "min" : "" %></p>

            <p><%= link_to 'Edit', 'editService/'+service.id , class: 'button' %><p>
            <%= button_to service.is_published ? 'Unpublish' : 'Publish', service_publish_path(service), method: :post, class: 'button' %>
            <%= button_to 'Delete', hide_service_path(service), method: :delete, id: "delete-service-#{service.id}", class: 'button' %>

            
        </div>
        </div>
        <% end %>

       
    
    </div>
  </body>
</html>

app/views/services/new.html.erb
<html>
  <head>
    <title>Service</title>
    <%= stylesheet_link_tag 'edit_service', media: 'all' %>
  </head>
  <body>
    <div class="service-container">
      <h1>New Service</h1>

      <%= form_with(model: @service, url: services_path, local: true) do |form| %>
        <% if @service.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

            <ul>
              <% @service.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <%= form.label :name %>
        <%= form.text_field :name %>

        <%= form.label :short_description %>
        <%= form.text_area :short_description , class: 'ip'%>

        <%= form.label :description %>
        <%= form.text_area :description , class: 'ip'%>

        <%= form.label :price %>
        <div class="field-unit-wrapper">
          <p>$</p>
          <%= form.number_field :price, { step: 0.01, class: 'ip', style: 'margin: 0'} %>
        </div>
        <%= form.label :duration %>
        <div class="field-unit-wrapper">
          <%= form.number_field :duration , { class: 'ip input-no-margin', style: 'margin: 0' } %>
          <p>minutes</p>
        </div>

        <div style="display: flex; gap: 20px">
          <%= link_to 'Cancel', servicesindex_path, class: 'button cancel-button' %>
          <%= form.submit "Create Service", class: 'button' %>
        </div>
      <% end %>
    </div>
  </body>
</html>

app/views/services/show.html.erb
<html>
  <head class='public-page-head'>
    <%= stylesheet_link_tag "purchase_service.css" %>
  </head>
  <body>
    <% if (@service.nil?) %>
      404: Service not found
    <% else %>
      <div class="service-container">
        <div class="header">
          <a href="/public/<%= @service_owner.username %>">← Back to <%= @service_owner.fname %> <%= @service_owner.lname %></a>
          <h3 class="service-title"><%= @service.name %></h3>
        </div>
        <div class="body">
          <p class="service-description"><%= @service.description %></p>
        </div>
        <div class="footer">
          <p class="service-price-duration"><%= "$#{format("%.2f", @service.price)} 
            for #{@service.duration / 60 > 0 ? (@service.duration / 60).to_s + " hour" : ""}
            #{@service.duration / 60 > 0 && @service.duration % 60 > 0 ? " and " : ""}
            #{@service.duration % 60 > 0 ? (@service.duration % 60).to_s + " minutes" : ""}" %></p>
          <%# <button url>Purchase</button> %>
           <%= link_to "Purchase", appointments_page_index_path(@username,@service.id), id: @service.name.gsub(' ', '_') ,class: 'button' %>
          
        </div>
      </div>
    <% end %>
  </body>
</html>