config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'edit_public_page/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'submitemail', to: 'email_submission#index'
  post 'send_email', to: 'email_submission#send_email'
  get 'reset/:token', to: 'password_reset#reset'
  post 'submit_reset', to: 'password_reset#change_password'

  root 'home#index'

  get '/login', to: 'sessions#new', as: 'sessions_new'
  post '/login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get '/dashboard', to: 'dashboard#main', as: 'dashboard'
  get '/dashboard/hours', to: 'hours#index', as: 'hours'
  get '/dashboard/hours/new', to: 'hours#new', as: 'new_hour'
  post '/dashboard/hours', to: 'hours#create', as: 'create_hour'
  delete '/dashboard/hours', to: 'hours#destroy', as: 'delete_hour'

  post '/services', to: 'services#create'
  get '/services', to: 'services#new'

  get '/public/:username/services/:id', to: 'services#show', as: 'show_service'

  delete '/deleteservices/:id/hide', to: 'services#hide', as: 'hide_service'
  post '/togglepublish/:id', to: 'services#togglepublish', as: 'service_publish'

  get '/servicesindex', to: 'services#index'

  post '/editService/:token', to: 'services#submit_edit'
  get 'editService/:token', to: 'services#edit_page', as: 'edit_service'

  get 'public/:username', to: 'public_page#show', as: 'public_page'
  get '/edit_public_page', to: 'edit_public_page#index', as: 'edit_public_page'

  get 'appointments/:id/edit', to: 'appointments#edit', as: 'edit_appointment'
  patch 'appointments/:id', to: 'appointments#update', as: 'update_appointment'
  delete 'appointments/:id', to: 'appointments#destroy', as: 'delete_appointment'

  get '/apts/:username', to: 'user_appointments#show', as: 'userappointments'

  patch '/update/user_profile', to: 'edit_public_page#update', as: 'edit_public_page_update'
  get '/public/:username/:service_id/create/appointment', to: 'appointments#index', as: 'appointments_page_index'
  post '/public/:username/:service_id/create/appointment/submit', to: 'appointments#create_submit',  as: 'appointments_page_create_submit'
  get '/appointment/get/timings/:username/:start_date', to: 'appointments#fetch_slot_times_api',  as: 'appointments_page_fetch_slot_times_for_date'
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  before_action :get_current_user
  before_action :redirect_if_logged_out

  private

  def get_current_user
    @current_user ||= User.find_by(user_id: session[:user_id])
  end

  def redirect_if_logged_out
    redirect_to login_url if @current_user.nil?
  end
end

app/views/dashboard/main.html.erb
<html>
  <head>
  <title>Dashboard</title>
    <%= stylesheet_link_tag 'dashboard', media: 'all' %>
  </head>
  <body>
  <div class="navbar">
    <h1 class="title">Dashboard</h1>
    <div class="navbar-links">
    <% @username = User.find_by(user_id: session[:user_id]).username %>
    <% if @username.present? %>
      <%= link_to 'Public Profile', public_page_path(@username) %>
    <% end %>
    <%= link_to 'Edit Public Profile', edit_public_page_path %>
    <%= link_to 'Logout', logout_path, method: :delete %>
  </div>
    
  </div>
  
    <% flash.each do |key, message|%>
      <div class="alert">
        <%= message%>
      </div>
    <%end%>
    <div class="dashboard-container">
    <center>
      <h1>Welcome to the Dashboard Page</h1>
      <p>Logged in as <%= @current_user.email %></p>
      
      <div class="square-items">
      
      
      <%= link_to 'Services', servicesindex_path, class: 'button'%>
      <%= link_to 'Availability', hours_path, class: 'button'%>
      <%= link_to 'Appointments', userappointments_path(username: @username), class: 'button'%>
      
      </div>
      </center>
    </div>
  </body>
</html>