config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'edit_public_page/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'submitemail', to: 'email_submission#index'
  post 'send_email', to: 'email_submission#send_email'
  get 'reset/:token', to: 'password_reset#reset'
  post 'submit_reset', to: 'password_reset#change_password'

  root 'home#index'

  get '/login', to: 'sessions#new', as: 'sessions_new'
  post '/login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get '/dashboard', to: 'dashboard#main', as: 'dashboard'
  get '/dashboard/hours', to: 'hours#index', as: 'hours'
  get '/dashboard/hours/new', to: 'hours#new', as: 'new_hour'
  post '/dashboard/hours', to: 'hours#create', as: 'create_hour'
  delete '/dashboard/hours', to: 'hours#destroy', as: 'delete_hour'

  post '/services', to: 'services#create'
  get '/services', to: 'services#new'

  get '/public/:username/services/:id', to: 'services#show', as: 'show_service'

  delete '/deleteservices/:id/hide', to: 'services#hide', as: 'hide_service'
  post '/togglepublish/:id', to: 'services#togglepublish', as: 'service_publish'

  get '/servicesindex', to: 'services#index'

  post '/editService/:token', to: 'services#submit_edit'
  get 'editService/:token', to: 'services#edit_page', as: 'edit_service'

  get 'public/:username', to: 'public_page#show', as: 'public_page'
  get '/edit_public_page', to: 'edit_public_page#index', as: 'edit_public_page'

  get 'appointments/:id/edit', to: 'appointments#edit', as: 'edit_appointment'
  patch 'appointments/:id', to: 'appointments#update', as: 'update_appointment'
  delete 'appointments/:id', to: 'appointments#destroy', as: 'delete_appointment'

  get '/apts/:username', to: 'user_appointments#show', as: 'userappointments'

  patch '/update/user_profile', to: 'edit_public_page#update', as: 'edit_public_page_update'
  get '/public/:username/:service_id/create/appointment', to: 'appointments#index', as: 'appointments_page_index'
  post '/public/:username/:service_id/create/appointment/submit', to: 'appointments#create_submit',  as: 'appointments_page_create_submit'
  get '/appointment/get/timings/:username/:start_date', to: 'appointments#fetch_slot_times_api',  as: 'appointments_page_fetch_slot_times_for_date'
end

app/models/hour.rb
# frozen_string_literal: true

class Hour < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :day, comparison: { greater_than_or_equal_to: 0, less_than: 7 }, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :times_must_be_fifteen_min_intervals
  validate :must_have_30_min_gap
  validate :times_must_not_overlap

  def times_must_be_fifteen_min_intervals
    errors.add(:start_time, 'start time must be on 15-minute interval') if start_time.nil? || start_time.min % 15 != 0
    return unless end_time.nil? || end_time.min % 15 != 0

    errors.add(:end_time, 'start time must be on 15-minute interval')
  end

  def must_have_30_min_gap
    return if start_time.nil? || end_time.nil?

    start_stamp = start_time.hour * 60 + start_time.min
    end_stamp = end_time.hour * 60 + end_time.min
    return unless end_stamp - start_stamp < 30

    errors.add(:end_time, 'must at least 30 minutes after start time')
  end

  def times_must_not_overlap
    return if start_time.nil? || end_time.nil?

    all_user_hours = Hour.where(user_id:)
    all_user_hours.each do |h|
      # ignore if different day
      next if day != h.day

      # calculate minutes since midnight
      start_stamp = start_time.hour * 60 + start_time.min
      end_stamp = end_time.hour * 60 + end_time.min
      h_start_stamp = h.start_time.hour * 60 + h.start_time.min
      h_end_stamp = h.end_time.hour * 60 + h.end_time.min
      # check position
      if start_stamp >= h_start_stamp && start_stamp <= h_end_stamp
        errors.add(:start_time, 'cannot overlap with another availability')
      end
      if end_stamp >= h_start_stamp && end_stamp <= h_end_stamp
        errors.add(:end_time, 'cannot overlap with another availability')
      end
      if start_stamp < h_start_stamp && end_stamp > h_end_stamp
        errors.add(:start_time, 'cannot overlap with another availability')
        errors.add(:end_time, 'cannot overlap with another availability')
      end
    end
  end
end

app/controllers/hours_controller.rb
# frozen_string_literal: true

class HoursController < ApplicationController
  before_action :get_current_user
  before_action :redirect_if_logged_out

  # GET /hours or /hours.json
  def index
    hours = Hour.where(user_id: @current_user.user_id)
    sorted = Array.new(7) { [] }
    hours.each do |h|
      sorted[h.day] << h
    end
    @days = sorted
  end

  # GET /hours/new
  def new
    @hour = Hour.new
    dayObject = Struct.new(:id, :day)
    @days = Date::DAYNAMES.map.with_index { |day, index| dayObject.new(index, day) }
  end

  # POST /hours or /hours.json
  def create
    dayObject = Struct.new(:id, :day)
    @days = Date::DAYNAMES.map.with_index { |day, index| dayObject.new(index, day) }
    @hour = @current_user.hours.new(hour_params)
    if @hour.save
      redirect_to hours_url, success: 'Time slot successfully added!'
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hours/1 or /hours/1.json
  def destroy
    @hour = @current_user.hours.find(params[:id])
    day_of_week = @hour.day
    start_time = @hour.start_time
    end_time = @hour.end_time
    # Find all appointments for the same day of the week as the hour
    appointments = Appointment.where("EXTRACT(DOW FROM startdatetime::date) = ? AND status = ?", day_of_week, "Booked")

    if appointments.any? { |appointment| appointment.startdatetime.strftime("%H:%M") >= @hour.start_time.strftime("%H:%M") && appointment.enddatetime.strftime("%H:%M") <= @hour.end_time.strftime("%H:%M") }
      redirect_to hours_url, error: "Cannot delete time slots for which appointments are booked"
    else
      if @current_user.hours.find(params[:id]).destroy
        redirect_to hours_url, success: 'Time slot successfully deleted!'
      else
        redirect_to hours_url, error: 'Time slot failed to delete.'
      end
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def hour_params
    params.require(:hour).permit(:day, :start_time, :end_time)
  end

  def get_current_user
    @current_user ||= User.find_by(user_id: session[:user_id])
  end

  def redirect_if_logged_out
    redirect_to login_url if @current_user.nil?
  end
end

app/views/hours/index.html.erb
<%= stylesheet_link_tag 'hour', media: 'all' %>
<div class="navbar">
    <h1 class="title">Availability</h1>
    <div class="navbar-links">
    <%= link_to "Add Availability", new_hour_path %>
    <%= link_to "Back to Dashboard", dashboard_path %>
    <%= link_to 'Logout', logout_path, method: :delete %>
    
  </div>
  </div>

<% flash.each do |key, message|%>
  <div class="alert">
    <%= message%>
  </div>
<%end%>

<div id="days" class="days-container">
  <% [0, 1, 2, 3, 4, 5, 6].each do |day| %>
    <div class="day-container">
      <h2><%= ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"][day] %>:</h2>
      <div class="times-container">
        <% if @days[day].length > 0 %>
          <% @days[day].sort_by(&:start_time).each do |hour| %>
            <div class="time-container">
              <p><%= hour.start_time.strftime("%l:%M%P") %> - <%= hour.end_time.strftime("%l:%M%P") %></p>
              <%= button_to 'Delete', delete_hour_path, method: :delete, params: {id: hour.id} %>
            </div>
          <% end %>
        <% else %>
          <p>No availability this day!</p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/hours/new.html.erb
<html>
  <head>
    <title>Edit Availability</title>
    <%= stylesheet_link_tag 'add_hour', media: 'all' %>
  </head>
  <body>
    <div class="hour-container">
<h1>New Availability</h1>

<%= form_with(model: @hour) do |form| %>
  <% if @hour.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@hour.errors.count, "error") %> prohibited this hour from being saved:</h2>

      <ul>
        <% @hour.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.collection_select :day, @days, :id, :day %>
  </div>

  <div>
    <%= form.label :start_time, style: "display: block" %>
    <div class="time-select">
      <%= form.time_select :start_time, {ampm: true, minute_step: 15, :default => {:hour => '00', :minute => '00'}} %>
    </div>
  </div>

  <div>
    <%= form.label :end_time, style: "display: block" %>
    <div class="time-select">
      <%= form.time_select :end_time, {ampm: true, minute_step: 15, :default => {:hour => '23', :minute => '45'}} %>
    </div>
  </div>

  <div>
    <%= form.submit "Create Availability" %>
  </div>
<% end %>



<div>
  <%= link_to "Back to hours", hours_path %>
</div>
</div>
</body>
</html>