config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'edit_public_page/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'submitemail', to: 'email_submission#index'
  post 'send_email', to: 'email_submission#send_email'
  get 'reset/:token', to: 'password_reset#reset'
  post 'submit_reset', to: 'password_reset#change_password'

  root 'home#index'

  get '/login', to: 'sessions#new', as: 'sessions_new'
  post '/login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get '/dashboard', to: 'dashboard#main', as: 'dashboard'
  get '/dashboard/hours', to: 'hours#index', as: 'hours'
  get '/dashboard/hours/new', to: 'hours#new', as: 'new_hour'
  post '/dashboard/hours', to: 'hours#create', as: 'create_hour'
  delete '/dashboard/hours', to: 'hours#destroy', as: 'delete_hour'

  post '/services', to: 'services#create'
  get '/services', to: 'services#new'

  get '/public/:username/services/:id', to: 'services#show', as: 'show_service'

  delete '/deleteservices/:id/hide', to: 'services#hide', as: 'hide_service'
  post '/togglepublish/:id', to: 'services#togglepublish', as: 'service_publish'

  get '/servicesindex', to: 'services#index'

  post '/editService/:token', to: 'services#submit_edit'
  get 'editService/:token', to: 'services#edit_page', as: 'edit_service'

  get 'public/:username', to: 'public_page#show', as: 'public_page'
  get '/edit_public_page', to: 'edit_public_page#index', as: 'edit_public_page'

  get 'appointments/:id/edit', to: 'appointments#edit', as: 'edit_appointment'
  patch 'appointments/:id', to: 'appointments#update', as: 'update_appointment'
  delete 'appointments/:id', to: 'appointments#destroy', as: 'delete_appointment'

  get '/apts/:username', to: 'user_appointments#show', as: 'userappointments'

  patch '/update/user_profile', to: 'edit_public_page#update', as: 'edit_public_page_update'
  get '/public/:username/:service_id/create/appointment', to: 'appointments#index', as: 'appointments_page_index'
  post '/public/:username/:service_id/create/appointment/submit', to: 'appointments#create_submit',  as: 'appointments_page_create_submit'
  get '/appointment/get/timings/:username/:start_date', to: 'appointments#fetch_slot_times_api',  as: 'appointments_page_fetch_slot_times_for_date'
end

app/controllers/public_page_controller.rb
# frozen_string_literal: true

class PublicPageController < ApplicationController
  def show
    @username = params[:username]
    @user = User.find_by(username: @username)
    if @user.present?
      @services = Service.where(hidden: false, is_published: true)
      render 'public_page/user_public_page'
    else
      render 'public_page/user_not_found'
    end
  end
end

app/helpers/public_page_helper.rb
# frozen_string_literal: true

module PublicPageHelper
end

app/views/public_page/_service.html.erb
<a id="<%= service.name.gsub(' ', '_') %>" href="<%= show_service_path(data,service) %>" class="service">
  <h3 class="service-title"><%= service.name %></h3>
  <p class="service-description"><%= service.short_description %></p>
  <p class="service-price-duration"><%= "$#{format("%.2f", service.price)} 
    for #{service.duration / 60 > 0 ? (service.duration / 60).to_s + " hour" : ""}
    #{service.duration / 60 > 0 && service.duration % 60 > 0 ? " and " : ""}
    #{service.duration % 60 > 0 ? (service.duration % 60).to_s + " minutes" : ""}" %></p>
</a>

app/views/public_page/user_not_found.html.erb
<html>
    <head>
        <title>User Not Found</title>
        <%= stylesheet_link_tag "user_not_found.css" %>
    </head>
    <body>
        <div>User <%= @username %> does not exist or does not have a public page set up.</div><br>
        
        
        <%= link_to 'Return to dashboard', root_path, :class => 'return-to-dash-link' %>
        </div>
        
    </body>
</html>

app/views/public_page/user_public_page.html.erb
<html class='public-page-html'>
    <head class='public-page-head'>
        <%= stylesheet_link_tag "public_page.css" %>
    </head>
    <body class='public-page-body'>
        <aside class='public-page-aside'>
            <h2 class="user-full-name"><%= "#{@user.fname} #{@user.lname}" %> </h2>
            <p class="user-description"><%= @user.about %></p>
        </aside>
        <main class='public-page-main'>
            <ul class="service-list">
                <%= render partial: 'service', collection: @services, locals: { data: @user.username } %>
            </ul>
            <% if flash[:success].present? %> 
            <div class="flash-success">
                <%= flash[:success] %>
            </div>
        <% end %>
        </main>
    </body>
</html>